version: "3"

services:
  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  
  app:
    build: .
    ports:
      - 4000:3000
    environment:
      APPLICATION_NAME: Simple-CRUD-API
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017/Node-API
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
